print('-----------------')
print('    Data Diri    ')
print('-----------------')
nm = input('Nama                 : ')
al = input('Alamat               : ')
ttl = input('Tempat Tanggal Lahir : ')
jk = input('Jenis Kelamin        : ')
ag = input('Agama                : ')
pk = input('Pekerjaan            : ')
jr = input('Jurusan              : ')
un = input('Universitas          : ')
nt = input('Nomor Telpon         : ')
hb = input('Hobby                : ')
print()
print()
print()
print('==========================')
print('      Data Diri Anda      ')
print('==========================')
print('Nama                  : ',nm)
print('Alamat                : ',al)
print('Tempat Tanggal Lahir  : ',ttl)
print('Jenis Kelamin         : ',jk)
print('Pekerjaan             : ',pk)
print('Jurusan               : ',jr)
print('Universitas           : ',un)
print('Nomor Telpon          : ',nt)
print('Hobby                 : ',hb)
